name: PaintMatch
options:
  bundleIdPrefix: com.shimondeitel.paintmatch
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  PaintMatch:
    type: application
    platform: iOS
    sources:
      - path: PaintMatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.paintmatch
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: PaintMatch/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  PaintMatchTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PaintMatchTests
      - path: PaintMatch.storekit
    dependencies:
      - target: PaintMatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.paintmatch.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  PaintMatchUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PaintMatchUITests
    dependencies:
      - target: PaintMatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.paintmatch.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  PaintMatch:
    build:
      targets:
        PaintMatch: all
        PaintMatchTests: [test]
        PaintMatchUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: PaintMatch.storekit
    test:
      config: Debug
      storeKitConfiguration: PaintMatch.storekit
      targets:
        - PaintMatchTests
        - PaintMatchUITests
    archive:
      config: Release
